import type { Metadata } from "next";
import {Rajdhani} from "next/font/google";
import "./globals.css";

import RootComponent from "./RootComponent";

const rajdhaniFont = Rajdhani({
  variable: "--font-Rajdhani",
  subsets: ["latin"],
  weight: "300"
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rajdhaniFont.variable} `}
      >
        <RootComponent>{children}</RootComponent>
      </body>
    </html>
  );
}
